_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.13.9
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
            "2":
                - 1
                - 5
                - 53
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
                - 62
            "4": 3.13.9
            "5": 0.19.11
            "8":
                - 3
                - 5
            "12": 0.19.11
            "13": windows-amd64
batch_size:
    value: 512
checkpoint_every:
    value: 5
checkpoint_path:
    value: ./lstm_checkpoint.pth
data_dir:
    value: F:\Raw RL Esports Replays\Day 3 Swiss Stage\Round 1\split_dataset
epochs:
    value: 2
hidden_dim:
    value: 128
learning_rate:
    value: 0.001
no_cuda:
    value: false
num_layers:
    value: 1
num_workers:
    value: 8
resume:
    value: false
run_name:
    value: null
wandb_project:
    value: rl-lstm-test
